import argparse
import json
from pathlib import Path
from typing import Sequence

from apsara_cli.cli.options import resolve_value, resolve_workspace
from apsara_cli.cli.session import get_sessions_dir, list_sessions, sanitize_session_name
from apsara_cli.cli.ui import ConsoleUI, default_use_color


def render_project_config_toml(
    workspace_root: Path,
    model: str,
    session: str,
    use_color: bool,
) -> str:
    color_value = "true" if use_color else "false"
    return "\n".join([
        "# Project-local Apsara configuration",
        "# Generated by `apsara init`.",
        "",
        "[defaults]",
        f'workspace = {json.dumps(str(workspace_root))}',
        f'model = {json.dumps(model)}',
        f'session = {json.dumps(sanitize_session_name(session))}',
        "stateless = false",
        "allow_bash = false",
        "auto_approve = false",
        f"color = {color_value}",
        "",
        "[ui]",
        'welcome_title = "Welcome to Apsara Agentic"',
        'welcome_subtitle = "Your local coding assistant"',
        'powered_by = "Powered by Bondeth"',
        "welcome_animation = true",
        "welcome_frame_delay_ms = 22",
        "",
    ])


def ensure_gitignore_entries(workspace_root: Path, entries: Sequence[str]) -> list[str]:
    gitignore_path = workspace_root / ".gitignore"
    existing_lines = (
        gitignore_path.read_text(encoding="utf-8").splitlines()
        if gitignore_path.exists()
        else []
    )
    normalized = {line.strip() for line in existing_lines}
    missing_entries = [entry for entry in entries if entry not in normalized]
    if not missing_entries:
        return []

    updated_lines = list(existing_lines)
    if updated_lines and updated_lines[-1].strip():
        updated_lines.append("")
    if "# Apsara" not in normalized:
        updated_lines.append("# Apsara")
    updated_lines.extend(missing_entries)
    gitignore_path.write_text("\n".join(updated_lines) + "\n", encoding="utf-8")
    return missing_entries


async def init_workspace(args: argparse.Namespace, config: object) -> int:
    from apsara_cli.config.settings import load_cli_config, project_config_path

    use_color = bool(resolve_value(args.color, config.defaults.color, default_use_color()))
    ui = ConsoleUI(use_color=use_color)

    workspace_root = resolve_workspace(args.workspace or ".")
    workspace_root.mkdir(parents=True, exist_ok=True)

    model = str(resolve_value(args.model, config.defaults.model, "gpt-5.4-mini"))
    session_name = str(resolve_value(args.session, config.defaults.session, "default"))
    config_path = project_config_path(workspace_root)

    if config_path.exists() and not args.force:
        ui.info(f"Apsara is already initialized in {workspace_root}")
        ui.info(f"Using existing project config at {config_path}")
    else:
        config_path.parent.mkdir(parents=True, exist_ok=True)
        config_text = render_project_config_toml(workspace_root, model, session_name, use_color)
        config_path.write_text(config_text, encoding="utf-8")
        ui.success(f"Initialized Apsara in {workspace_root}")
        ui.info(f"Created project config at {config_path}")

    added = ensure_gitignore_entries(workspace_root, [".apsara/", ".apsara-cli/"])
    if added:
        ui.info("Updated .gitignore with " + ", ".join(added))

    if not (workspace_root / ".env").exists():
        ui.warning("No .env file was found in this project. Add OPENAI_API_KEY before live model use.")

    if args.no_chat:
        ui.info("Project initialized. Next time, run `apsara chat` in this folder.")
        return 0

    ui.info("Starting Apsara in this project...")
    init_args = argparse.Namespace(**vars(args))
    init_args.command = "chat"
    init_args.workspace = str(workspace_root)
    initialized_config = load_cli_config(str(config_path), str(workspace_root))

    from apsara_cli.cli.chat import chat_loop
    return await chat_loop(init_args, initialized_config)


def print_sessions(args: argparse.Namespace, config: object) -> int:
    workspace_value = resolve_value(args.workspace, config.defaults.workspace, ".")
    workspace_root = resolve_workspace(str(workspace_value))
    sessions = list_sessions(workspace_root)
    if not sessions:
        print(f"No sessions found in {get_sessions_dir(workspace_root)}")
        return 0

    for session_path in sessions:
        print(session_path.stem)
    return 0
